# Docker Compose file for Vapor
#
# Install Docker on your system to run and test
# your Vapor app in a production-like environment.
#
# Note: This file is intended for testing and does not
# implement best practices for a production deployment.
#
# Learn more: https://docs.docker.com/compose/reference/
#
#   Build images: docker-compose build
#      Start app: docker-compose up app
# Start database: docker-compose up db
# Run migrations: docker-compose run migrate
#       Stop all: docker-compose down (add -v to wipe db)
#
version: '3.7'

services:
  app:
    image: cheers-gateway:latest
    build:
      context: .
    env_file:
      - .env.production
    ports:
      - '8080:55688'
    # user: '0' # uncomment to run as root for testing purposes even though Dockerfile defines 'vapor' user.
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
  migrate:
    image: cheers-gateway:latest
    build:
      context: .
    env_file:
      - .env.production
    command: ["migrate", "--yes"]
    deploy:
      replicas: 0
  revert:
    image: cheers-gateway:latest
    build:
      context: .
    env_file:
      - .env.production
    command: ["migrate", "--revert", "--yes"]
    deploy:
      replicas: 0
