name: release
on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions: write-all

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: "0"
          fetch-tags: true

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.69.0
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          PRERELEASE: false
          DEFAULT_BUMP: patch
          MAJOR_STRING_TOKEN: "feat!:"
          MINOR_STRING_TOKEN: "feat:"
          PATCH_STRING_TOKEN: "fix:"

      - name: Show version
        run: echo ${{ steps.tag.outputs.new_tag }}

      - name: Generate Changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@v1.6.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          head-ref: ${{ steps.tag.outputs.new_tag }}
          filter-author: (dependabot\[bot\]|Renovate Bot)
          filter: '([R|r]elease[d]\s+[v|V]\d(\.\d+){0,2})|Prettified|Merge branch'

      - name: Create Release
        uses: ncipollo/release-action@v1
        if: steps.tag.outputs.new_tag
        with:
          name: ${{ steps.tag.outputs.new_tag }}
          tag: ${{ steps.tag.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ${{ steps.changelog.outputs.compareurl }}
            ${{ steps.changelog.outputs.changelog }}